# Generated by Django 3.2.4 on 2024-04-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fee_vourcher',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='fee_vourcher',
            name='student',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='Semester',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='class_id',
            new_name='related_class',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='class_id',
            new_name='related_class',
        ),
        migrations.AlterField(
            model_name='student',
            name='cnic',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['year', 'semester'], name='app_class_year_bc3f03_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['class_room'], name='app_classro_class_r_2c0534_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['GPA'], name='app_result_GPA_3b2dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_no', 'cnic'], name='app_student_registr_0a2547_idx'),
        ),
        migrations.DeleteModel(
            name='Fee_vourcher',
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='related_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AddIndex(
            model_name='feevoucher',
            index=models.Index(fields=['amount'], name='app_feevouc_amount_5ccc6e_idx'),
        ),
    ]
